version: '3'

services:
  postgres:
    build:
      context: ./docker
      dockerfile: Dockerfile-pg
    environment:
      - 'POSTGRES_DB=etutor_sql'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=etutor_sql'
    ports:
      - '5434:5432'
