# Logging
logging:
  level:
    ROOT: info
    at.jku.dke: trace

# Data
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/etutor_sql
    username: etutor_sql
    password: secret
  jpa:
    show-sql: true

# Springdoc
springdoc:
  show-actuator: true

# API key definition
clients:
  api-keys:
    - name: task-administration
      key: task-admin-key
      roles:
        - CRUD
        - SUBMIT
    - name: jobe-server
      key: jobe-server-key
      roles:
        - SUBMIT
    - name: plag-check
      key: plag-check-key
      roles:
        - READ_SUBMISSION

# JDBC
jdbc:
  url: jdbc:postgresql://localhost:5434/etutor_sql_exercises
  admin:
    username: etutor_sql
    password: secret
  executor:
    username: etutor_sql_executor
    password: etutor_sql_executor_pwd
  max-pool-size: 5
  max-lifetime: 1800000 # 30 minutes
  connection-timeout: 15000 # 15 seconds

sql-url: http://localhost:8080/api/forwardPublic/sql/query/
