# Logging
logging:
  level:
    ROOT: info

# Server
server:
  shutdown: GRACEFUL

# Springdoc
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

# Spring
spring:
  jpa:
    show-sql: false

# JDBC
jdbc:
  max-pool-size: 15
  max-lifetime: 1800000 # 30 minutes
  connection-timeout: 15000 # 15 seconds

# Specify the following settings via environment variables in the docker container.
## Database
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5434/etutor_sql
#    username: etutor
#    password: TBD
#  flyway:
#    user: etutor_sql_admin
#    password: TBD
#
## API key definition
#clients:
#  api-keys:
#    - name: task-administration
#      key: TBD
#      roles:
#       - CRUD
#       - SUBMIT
#    - name: jobe-server
#      key: TBD
#      roles:
#       - SUBMIT
#    - name: plag-check
#      key: TBD
#      roles:
#       - READ_SUBMISSION
## JDBC
#jdbc:
#  url: jdbc:postgresql://localhost:5434/etutor_sql_exercises
#  admin:
#    username: etutor_sql_schema_manager
#    password: TBD
#  executor:
#    username: etutor_sql_executor
#    password: TBD
#sql-url: https://etutor.dke.uni-linz.ac.at/api/forwardPublic/sql/query/
