FROM postgres:16

# Custom initialization scripts
COPY ./create_user.sh       /docker-entrypoint-initdb.d/900-create_user.sh
COPY ./create_database.sh   /docker-entrypoint-initdb.d/901-create_database.sh
